/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 room.gltf 
Author: Garu Games (https://sketchfab.com/garugames)
License: SKETCHFAB Editorial (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-80s-hacker-room-081a73b15f104a1b82c57874d4205c04
Title: Low Poly 80's Hacker Room 🕹️
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function HackerRoom(props) {
  const { nodes, materials } = useGLTF("room.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.336, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Wall} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Floor} />
      </group>
      <group position={[-3.102, 0, 2.687]} scale={0.818}>
        <group position={[1.1, 2.821, 0.632]} rotation={[0, 0, -0.244]}>
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.material}
          />
        </group>
        <group position={[1.1, 2.821, -0.675]} rotation={[0, 0, -0.244]}>
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials.material}
          />
        </group>
        <mesh geometry={nodes.Object_9.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Arcade_screen}
        />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Glow} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Logo} />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.Yellow_Glow}
          position={[0.814, 2.827, 0.268]}
          rotation={[0, 0, -0.244]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.Yellow_Glow}
          position={[0.814, 2.827, -1.039]}
          rotation={[0, 0, -0.244]}
        />
      </group>
      <group
        position={[0.2, 0.33, 0.13]}
        rotation={[0, -0.449, 0]}
        scale={1.167}
      >
        <group position={[0, 1.406, 0]} scale={1.192}>
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials.Black}
            rotation={[0, 1.548, 0]}
            scale={0.839}
          />
        </group>
        <mesh geometry={nodes.Object_24.geometry} material={materials.Metal} />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.Black}
          position={[0, 0.002, 0]}
        />
      </group>
      <group position={[-4, 4.958, -1.152]} rotation={[-0.191, 0, 0]}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.White} />
      </group>
      <group position={[-4, 4.935, -1.379]} scale={[0.927, 0.898, 0.66]}>
        <mesh geometry={nodes.Object_39.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.White} />
      </group>
      <group position={[-4, 4.935, -1.465]} scale={0.956}>
        <mesh geometry={nodes.Object_42.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.White} />
      </group>
      <group position={[-4, 4.935, -1.592]} scale={[0.927, 1.098, 0.66]}>
        <mesh geometry={nodes.Object_45.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.White} />
      </group>
      <group position={[-4, 4.935, -1.68]} scale={0.956}>
        <mesh geometry={nodes.Object_48.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.White} />
      </group>
      <group
        position={[-4, 4.935, -1.847]}
        rotation={[0.086, 0, 0]}
        scale={[0.956, 1.045, 0.956]}
      >
        <mesh geometry={nodes.Object_51.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.White} />
      </group>
      <group position={[-4, 4.935, -1.968]} scale={[0.927, 0.898, 0.512]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.White} />
      </group>
      <group position={[-4, 4.935, -2.038]} scale={0.956}>
        <mesh geometry={nodes.Object_57.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.White} />
      </group>
      <group position={[-4, 4.935, -2.162]} scale={[0.927, 1.098, 0.66]}>
        <mesh geometry={nodes.Object_60.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.White} />
      </group>
      <group position={[-4, 4.935, -2.251]} scale={[0.927, 0.898, 0.66]}>
        <mesh geometry={nodes.Object_63.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.White} />
      </group>
      <group
        position={[-4, 4.935, -2.414]}
        rotation={[0.15, 0, 0]}
        scale={[0.956, 1.043, 0.475]}
      >
        <mesh geometry={nodes.Object_66.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.White} />
      </group>
      <group
        position={[-3.286, 5.053, -2.991]}
        rotation={[-Math.PI / 2, 0, 2.415]}
        scale={0.956}
      >
        <mesh geometry={nodes.Object_69.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.White} />
      </group>
      <group
        position={[-3.301, 5.134, -3.052]}
        rotation={[-Math.PI / 2, 0, 2.617]}
        scale={[0.892, 0.952, 0.66]}
      >
        <mesh geometry={nodes.Object_72.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.White} />
      </group>
      <group
        position={[-3.425, 5.216, -3.12]}
        rotation={[-Math.PI / 2, 0, 2.99]}
        scale={[0.932, 0.898, 0.66]}
      >
        <mesh geometry={nodes.Object_75.geometry} material={materials.Book} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.White} />
      </group>
      <group
        position={[-1.729, 2.026, -1.956]}
        rotation={[0, 0.707, 0]}
        scale={1.325}
      >
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials["Computer-beige"]}
        />
        <mesh
          geometry={nodes.Object_80.geometry}
          material={materials.Grey}
          position={[-0.03, -0.001, 0.012]}
          rotation={[0.103, 0, 0]}
        />
      </group>
      <group
        position={[2.311, 2.742, -3.897]}
        rotation={[1.483, -Math.PI / 2, 0]}
        scale={1.325}
      >
        <mesh
          geometry={nodes.Object_82.geometry}
          material={materials["Computer-beige"]}
        />
        <mesh
          geometry={nodes.Object_84.geometry}
          material={materials.Grey}
          rotation={[0.093, 0, 0]}
        />
      </group>
      <group
        position={[-3.505, 1.989, -1.612]}
        rotation={[0, 1.386, 0]}
        scale={1.204}
      >
        <group
          position={[0, 1.212, 0.459]}
          rotation={[-0.751, 0, 0]}
          scale={0.735}
        >
          <mesh
            geometry={nodes.Object_88.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_90.geometry}
            material={materials.material_0}
            position={[0, -0.209, 0]}
            rotation={[0.696, -1.228, 0]}
            scale={1.361}
          />
        </group>
        <mesh
          geometry={nodes.Object_86.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_92.geometry}
          material={materials.Black}
          position={[0, 0.046, 0]}
        />
      </group>
      <group position={[-0.803, 4.286, -4]}>
        <mesh geometry={nodes.Object_98.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Object_99.geometry}
          material={materials.Poster1}
        />
      </group>
      <group
        position={[2.233, 4.286, -4]}
        rotation={[0, 0, 0.159]}
        scale={0.699}
      >
        <mesh
          geometry={nodes.Object_101.geometry}
          material={materials["Black-gloss"]}
        />
        <mesh
          geometry={nodes.Object_102.geometry}
          material={materials.Poster2}
        />
      </group>
      <group position={[-3.642, 4.935, -0.731]} rotation={[0, 0.293, 0]}>
        <mesh geometry={nodes.Object_106.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Object_108.geometry}
          material={materials["Black-gloss"]}
        />
      </group>
      <group position={[-3.601, 4.935, -3.663]} rotation={[0, -0.5, 0]}>
        <mesh geometry={nodes.Object_110.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Object_112.geometry}
          material={materials["Black-gloss"]}
        />
      </group>
      <group
        position={[-2.754, -0.174, -1.52]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.86}
      >
        <group
          position={[-1.514, 2.516, -0.56]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.163}
        >
          <mesh
            geometry={nodes.Object_116.geometry}
            material={materials["Computer-beige"]}
          />
          <mesh
            geometry={nodes.Object_117.geometry}
            material={materials["Screen-dos"]}
          />
          <mesh
            geometry={nodes.Object_119.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Object_120.geometry}
            material={materials["Computer-beige"]}
          />
          <mesh
            geometry={nodes.Object_121.geometry}
            material={materials.Grey}
          />
          <mesh
            geometry={nodes.Object_123.geometry}
            material={materials.Grey}
            position={[0.353, 0.172, -0.112]}
            rotation={[Math.PI / 2, 1.395, -Math.PI / 2]}
            scale={1.325}
          />
        </group>
        <group
          position={[1.619, 2.516, -0.229]}
          rotation={[0, -0.643, 0]}
          scale={1.423}
        >
          <group position={[-0.448, 0.11, 0.426]}>
            <mesh
              geometry={nodes.Object_133.geometry}
              material={materials["Computer-beige"]}
            />
            <mesh
              geometry={nodes.Object_134.geometry}
              material={materials.Yellow_Glow}
            />
          </group>
          <group position={[-0.412, 0.11, 0.426]}>
            <mesh
              geometry={nodes.Object_136.geometry}
              material={materials["Computer-beige"]}
            />
            <mesh
              geometry={nodes.Object_137.geometry}
              material={materials.Yellow_Glow}
            />
          </group>
          <group position={[0.015, 0.265, 0.045]} scale={1.224}>
            <mesh
              geometry={nodes.Object_139.geometry}
              material={materials["Computer-beige"]}
            />
            <mesh
              geometry={nodes.Object_140.geometry}
              material={materials["Screen-nc"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_125.geometry}
            material={materials["Computer-beige"]}
          />
          <mesh
            geometry={nodes.Object_127.geometry}
            material={materials["Computer-beige"]}
          />
          <mesh
            geometry={nodes.Object_129.geometry}
            material={materials.Black}
            position={[0, 0, -0.102]}
          />
          <mesh
            geometry={nodes.Object_131.geometry}
            material={materials.material}
            position={[0.402, 0.177, 0.422]}
            rotation={[-0.106, 0, 0]}
          />
        </group>
        <mesh geometry={nodes.Object_114.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Object_142.geometry}
          material={materials.Wood}
          scale={1.182}
        />
      </group>
      <group position={[0.867, -0.174, -2.859]} scale={0.86}>
        <group position={[-2.027, 2.516, -0.691]} scale={1.423}>
          <group position={[-0.448, 0.11, 0.426]}>
            <mesh
              geometry={nodes.Object_154.geometry}
              material={materials["Computer-beige"]}
            />
            <mesh
              geometry={nodes.Object_155.geometry}
              material={materials.Yellow_Glow}
            />
          </group>
          <group position={[-0.412, 0.11, 0.426]}>
            <mesh
              geometry={nodes.Object_157.geometry}
              material={materials["Computer-beige"]}
            />
            <mesh
              geometry={nodes.Object_158.geometry}
              material={materials.Yellow_Glow}
            />
          </group>
          <group position={[0.015, 0.265, 0.045]}>
            <mesh
              geometry={nodes.Object_160.geometry}
              material={materials["Computer-beige"]}
            />
            <mesh
              geometry={nodes.Object_161.geometry}
              material={materials["Screen-qb"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_146.geometry}
            material={materials["Computer-beige"]}
          />
          <mesh
            geometry={nodes.Object_148.geometry}
            material={materials["Computer-beige"]}
          />
          <mesh
            geometry={nodes.Object_150.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Object_152.geometry}
            material={materials.material}
            position={[0.402, 0.177, 0.422]}
            rotation={[-0.106, 0, 0]}
          />
        </group>
        <group
          position={[0.279, 2.516, -0.342]}
          rotation={[0, -0.174, 0]}
          scale={0.862}
        >
          <group
            position={[-0.077, 1.275, -0.019]}
            rotation={[0, 0.061, 0]}
            scale={1.76}
          >
            <mesh
              geometry={nodes.Object_169.geometry}
              material={materials.Grey}
            />
            <mesh
              geometry={nodes.Object_171.geometry}
              material={materials.Grey}
            />
            <mesh
              geometry={nodes.Object_172.geometry}
              material={materials.Yellow_Glow}
            />
            <mesh
              geometry={nodes.Object_174.geometry}
              material={materials.Black}
              position={[-0.171, 0.181, 0.294]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_176.geometry}
              material={materials.Black}
              position={[-0.001, 0, -0.115]}
            />
            <mesh
              geometry={nodes.Object_178.geometry}
              material={materials.Grey}
            />
            <mesh
              geometry={nodes.Object_180.geometry}
              material={materials.Black}
            />
            <mesh
              geometry={nodes.Object_182.geometry}
              material={materials.Yellow_Glow}
              position={[0.478, 0.028, 0.321]}
            />
            <mesh
              geometry={nodes.Object_184.geometry}
              material={materials.Black}
              position={[0.361, 0.313, 0.077]}
              rotation={[0, -0.316, 0]}
            />
            <mesh
              geometry={nodes.Object_186.geometry}
              material={materials.Black}
              position={[0.361, 0.257, 0.077]}
              rotation={[0, -0.5, 0]}
            />
          </group>
          <group position={[0.73, 0.654, 0.528]}>
            <mesh
              geometry={nodes.Object_188.geometry}
              material={materials.Black}
            />
            <mesh
              geometry={nodes.Object_189.geometry}
              material={materials.Yellow_Glow}
            />
          </group>
          <mesh
            geometry={nodes.Object_167.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Object_191.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Object_192.geometry}
            material={materials.TV_screen}
          />
          <mesh
            geometry={nodes.Object_194.geometry}
            material={materials.Grey}
            position={[0, 0, -0.019]}
          />
        </group>
        <mesh geometry={nodes.Object_144.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Object_163.geometry}
          material={materials.Wood}
          scale={1.182}
        />
        <mesh
          geometry={nodes.Object_165.geometry}
          material={materials["Computer-beige"]}
          position={[-1.802, 2.516, 0.535]}
          scale={1.586}
        />
      </group>
      <group
        position={[2.85, -0.027, 0.269]}
        rotation={[-Math.PI, 1.052, -Math.PI]}
        scale={[0.638, 0.86, 0.638]}
      >
        <group
          position={[-0.599, 1.144, 0.477]}
          rotation={[0, 1.06, 0]}
          scale={[1.567, 1.163, 1.567]}
        >
          <mesh
            geometry={nodes.Object_198.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_200.geometry}
            material={materials.material_0}
            position={[-0.057, -0.001, -0.011]}
            rotation={[0, -0.197, 0]}
          />
          <mesh
            geometry={nodes.Object_202.geometry}
            material={materials.material_0}
            position={[0.198, 0.001, 0.13]}
            rotation={[0, -0.978, 0]}
          />
        </group>
        <mesh geometry={nodes.Object_196.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Object_204.geometry}
          material={materials.Wood}
          scale={1.182}
        />
      </group>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.material}
        position={[4, 0.336, 4]}
        scale={[1.284, 1.351, 1.284]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.Grey}
        position={[-2.411, 0.338, -0.29]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.Wood}
        position={[-4, 4.821, -2.204]}
      />
      <mesh
        geometry={nodes.Object_94.geometry}
        material={materials.material_0}
        position={[-3.999, 4.53, 0.584]}
        rotation={[-2.935, 0, -Math.PI / 2]}
        scale={3.502}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.material_0}
        position={[-3.937, 4.112, -0.006]}
        rotation={[3.088, 0, -Math.PI / 2]}
        scale={2.119}
      />
      <mesh
        geometry={nodes.Object_104.geometry}
        material={materials.material_18}
        position={[0, 0.036, 0]}
        scale={21.226}
      />
      <mesh
        geometry={nodes.Object_206.geometry}
        material={materials.Metal}
        position={[-3.716, 6.41, 0]}
      />
      <mesh
        geometry={nodes.Object_208.geometry}
        material={materials.Metal}
        position={[-3.716, 6.41, 4]}
      />
      <mesh
        geometry={nodes.Object_210.geometry}
        material={materials.Metal}
        position={[0.126, 0, 3.652]}
      />
      <mesh
        geometry={nodes.Object_212.geometry}
        material={materials["Computer-beige"]}
        position={[-2.037, 2, -3.274]}
      />
      <mesh
        geometry={nodes.Object_214.geometry}
        material={materials.material_0}
        position={[-2.999, 2.001, -2.319]}
      />
      <mesh
        geometry={nodes.Object_216.geometry}
        material={materials.Black}
        position={[1.565, 2.89, -3.46]}
        rotation={[0, 0.187, 0]}
      />
      <mesh
        geometry={nodes.Object_218.geometry}
        material={materials.Black}
        position={[2.815, 2.139, -3.764]}
      />
      <mesh
        geometry={nodes.Object_220.geometry}
        material={materials["Black-gloss"]}
        position={[-3.939, 5.357, -0.629]}
      />
    </group>
  );
}

useGLTF.preload("/room.gltf");
